Cross-tests for PF's Configure (#2467)
The interface for configure cross-tests is:
```go
func Configure(
    t *testing.T, 
    schema schema.Schema,          // The provider's schema
    tfConfig map[string]cty.Value, // Config values for HCL/TF
    puConfig resource.PropertyMap, // Config values for Pulumi YAML/Pulumi
)
```

Because the mapping between `tfConfig` and `puConfig` is non-trivial,
and to allow for secret injection, I have chosen to allow setting
`tfConfig` and `puConfig` separately.

This is a pre-requisite for #2440.

---

When the underlying provider configuration doesn't match between Pulumi
and TF, the error looks like this:

```go
func TestFailure(t *testing.T) {
	crosstests.Configure(t,
		schema.Schema{Attributes: map[string]schema.Attribute{
			"k": schema.StringAttribute{Optional: true},
		}},
		map[string]cty.Value{"k": cty.StringVal("foo")},
		resource.PropertyMap{"k": resource.NewProperty("oo")},
	)
}
```

```
go test -test.run \^TestFailure\$
warning: resource:test_res.Docs received a non-zero custom value &{ [32]     false false} that is being ignored. Plugin Framework based providers do not yet support this feature.
--- FAIL: TestFailure (2.25s)
    configure.go:129: Pulumi.yaml:
        backend:
            url: file://./data
        name: project
        resources:
            p:
                properties:
                    k: oo
                type: pulumi:providers:test
        runtime: yaml
    --- FAIL: TestFailure/compare (0.00s)
        configure.go:174: 
            	Error Trace:	/Users/ianwahbe/go/src/github.com/pulumi/pulumi-terraform-bridge/pf/tests/internal/cross-tests/configure.go:174
            	Error:      	Not equal: 
            	            	expected: tfsdk.Config{Raw:tftypes.Value{typ:tftypes.Object{AttributeTypes:map[string]tftypes.Type{"k":tftypes.primitive{name:"String", _:[]struct {}(nil)}}, OptionalAttributes:map[string]struct {}(nil), _:[]struct {}(nil)}, value:map[string]tftypes.Value{"k":tftypes.Value{typ:tftypes.primitive{name:"String", _:[]struct {}(nil)}, value:"foo"}}}, Schema:schema.Schema{Attributes:map[string]schema.Attribute{"k":schema.StringAttribute{CustomType:basetypes.StringTypable(nil), Required:false, Optional:true, Sensitive:false, Description:"", MarkdownDescription:"", DeprecationMessage:"", Validators:[]validator.String(nil)}}, Blocks:map[string]schema.Block(nil), Description:"", MarkdownDescription:"", DeprecationMessage:""}}
            	            	actual  : tfsdk.Config{Raw:tftypes.Value{typ:tftypes.Object{AttributeTypes:map[string]tftypes.Type{"k":tftypes.primitive{name:"String", _:[]struct {}(nil)}}, OptionalAttributes:map[string]struct {}(nil), _:[]struct {}(nil)}, value:map[string]tftypes.Value{"k":tftypes.Value{typ:tftypes.primitive{name:"String", _:[]struct {}(nil)}, value:"oo"}}}, Schema:schema.Schema{Attributes:map[string]schema.Attribute{"k":schema.StringAttribute{CustomType:basetypes.StringTypable(nil), Required:false, Optional:true, Sensitive:false, Description:"", MarkdownDescription:"", DeprecationMessage:"", Validators:[]validator.String(nil)}}, Blocks:map[string]schema.Block(nil), Description:"", MarkdownDescription:"", DeprecationMessage:""}}
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -18,3 +18,3 @@
            	            	     },
            	            	-    value: (string) (len=3) "foo"
            	            	+    value: (string) (len=2) "oo"
            	            	    }
            	Test:       	TestFailure/compare
FAIL
exit status 1
FAIL	github.com/pulumi/pulumi-terraform-bridge/pf/tests	3.059s
```