Moving provider configuration from provider Configure to CheckConfig
There is no change of functionality here. Previously, we would see the following

```
▶ envchain pulumi-aws-ci pulumi up
Previewing update (dev):
     Type                     Name           Plan     Info
     pulumi:pulumi:Stack      checks-dev
     └─ pulumi:providers:aws  default_2_9_1           1 error

Diagnostics:
  pulumi:providers:aws (default_2_9_1):
    error: pulumi:providers:aws resource 'default_2_9_1's property 'aws:region' value {<nil>} has a problem: The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.
```

The new code path does the following:

```
▶ envchain pulumi-aws-ci pulumi up
Previewing update (dev):
     Type                     Name                                        Plan     Info
     pulumi:pulumi:Stack      checks-dev
     └─ pulumi:providers:aws  default_2_10_0_alpha_1592400278_ge84bbc90b           1 error

Diagnostics:
  pulumi:providers:aws (default_2_10_0_alpha_1592400278_ge84bbc90b):
    error: pulumi:providers:aws resource 'default_2_10_0_alpha_1592400278_ge84bbc90b's property 'aws:region' value {<nil>} has a problem: The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.

```

This just moves the validation earlier in the flow