Supply user error about which config values were missing
Fixes: #282

A regression removed this and it meant that when a user didn't
supply the correct config values, that they got the following error:

```
  aws:s3:Bucket (my-bucket):
    error: required configuration keys were missing
```

That had no context. Fixing the regression now shows this error:

```
  aws:s3:Bucket (my-bucket):
    error: 1 error occurred:
    	* missing required configuration key "aws:region": The region where AWS operations will take place. Examples are us-east-1, us-west-2, etc.
    Set a value using the command `pulumi config set aws:region <value>`.
```