Write a better error message for invalid schemas
Previously, when the bridge generated an invalid schema, it simply output the error given
by the returned diagnostic. For example:

```console
$ pulumi package get-schema terraform-provider NetApp/netapp-ontap
error: rpc error: code = Unknown desc = failed to create Pulumi schema: <nil>: #/resources/netapp-ontap:index~1protocolsSanLun-mapsResource:ProtocolsSanLun-mapsResource: doesn't validate with '/$defs/token'; , and 33 other diagnostic(s)
```

This isn't very useful, especially since JSON schema validation errors generate
different (and sometimes more helpful errors) for the same problem. For example, with this
change, running the same command generates a more helpful error:

```console
$ pulumi package get-schema terraform-provider NetApp/netapp-ontap
error: #/functions/netapp-ontap:index~1getProtocolsSanLun-mapsDataSource:getProtocolsSanLun-mapsDataSource: doesn't val
idate with '/$defs/token'

error: #/functions/netapp-ontap:index~1getProtocolsSanLun-mapsDataSource:getProtocolsSanLun-mapsDataSource: does not ma
tch pattern '^[a-zA-Z][-a-zA-Z0-9_]*:([^0-9][a-zA-Z0-9._/-]*)?:[^0-9][a-zA-Z0-9._/]*$'

error: #/functions/netapp-ontap:index~1getProtocolsSanLun-mapDataSource:getProtocolsSanLun-mapDataSource: doesn't valid
ate with '/$defs/token'

error: #/functions/netapp-ontap:index~1getProtocolsSanLun-mapDataSource:getProtocolsSanLun-mapDataSource: does not matc
h pattern '^[a-zA-Z][-a-zA-Z0-9_]*:([^0-9][a-zA-Z0-9._/-]*)?:[^0-9][a-zA-Z0-9._/]*$'

error: #/resources/netapp-ontap:index~1protocolsSanLun-mapsResource:ProtocolsSanLun-mapsResource: doesn't validate with
 '/$defs/token'

error: #/resources/netapp-ontap:index~1protocolsSanLun-mapsResource:ProtocolsSanLun-mapsResource: does not match patter
n '^[a-zA-Z][-a-zA-Z0-9_]*:([^0-9][a-zA-Z0-9._/-]*)?:[^0-9][a-zA-Z0-9._/]*$'

error: 28 additional errors

error: rpc error: code = Unknown desc = failed to create Pulumi schema: <nil>: #/functions/netapp-ontap:index~1getProto
colsSanLun-mapsDataSource:getProtocolsSanLun-mapsDataSource: doesn't validate with '/$defs/token'; , and 33 other diagn
ostic(s)
```

This was motivated by https://github.com/pulumi/pulumi-terraform-provider/issues/17

---

Without engine support for https://github.com/pulumi/pulumi/issues/16344, we are unable to
prevent the `error: rpc error: code = Unknown desc = ` section.