Ensure all variants of primitaves are covered in TF Schema Overrides
Currently, the type needed to be correct "int" or "boolean" and that
wasn't obvious in the TF providers. So we now cater for "integer" and
"bool" to ensure that they are now all defaulting to strings

Without these additional cases, we could end up in a statement of
DotNet getting the incorrect type (i.e a string when it expected a double)
and thus throwing an error as follows:

```
System.InvalidOperationException: Expected System.Double but got System.String deserializing Pulumi.Aws.LB.TargetGroup.deregistrationDelay
```