Make pre configure callback errors into failures (#1640)
Helps with https://github.com/pulumi/pulumi-aws/issues/2285

This removes the bad error message `error: rpc error: code = Unknown
desc =` and makes it more comprehensible: `pulumi:providers:aws resource
'default_6_18_2' has a problem:`


The error message was this before:
```
Diagnostics:
  pulumi:providers:aws (default):
    error: rpc error: code = Unknown desc = unable to validate AWS credentials.
    Details: failed to get shared config profile, aws
    Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.
```


The distinction between an error and a failure seems to be if it was
expected/unexpected IIUC. If that is true then this must be a failure
instead of an error.