Improve the error message when a Pulumi token is missing it's name
The old error message starts with:

```
panic: runtime error: index out of range [0] with length 0

goroutine 113 [running]:

main.providerInfo.MakeStandard.func3({0x10203f705?, 0x1?}, {0x0?, 0x1400074dd40?})

	/home/runner/work/pulumi-terraform-provider/pulumi-terraform-provider/bridge/pkg/tfbridge/tokens/tokens.go:51 +0x15c

github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge/tokens.KnownModules.knownResource.func1({0x10203f705?, 0x5?}, {0x0?, 0x5?}, 0x1400074dd40, {0x0?, 0x0?})
```

The new message looks like this:

```
error: parameterize: rpc error: code = Unknown desc = 1 error occurred:
        * resources:
1 error occurred:
        * "materialize_index": empty name for module "index"
```