Fix Python comment indentation
In some situations, the raw comments for Python packages was being
generated incorrectly.  Because Python is sensitive to whitespace,
this meant some packages wouldn't parse; e.g.

      File "/.../python2.7/site-packages/pulumi_kubernetes/daemon_set.py", line 27
        __props__['metadata'] = metadata
        ^
    IndentationError: unexpected indent

The fix is trivial.